In [ ]:
print("hello world")

hello world


In [ ]:
import numpy as np
a=np.eye (4)
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
import numpy as np
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
import numpy as np
a=np.empty((10,10))
print(a)

[[1.85170527e-315 0.00000000e+000 1.91077771e+214 7.39609060e+097
  1.27661731e-152 7.82764396e+194 5.98129924e-154 9.75394660e+199
  7.67112743e+170 2.06917493e+161]
 [3.03387744e-152 2.31462827e-152 2.31462645e-152 1.27734658e-152
  1.42853563e+248 2.28690939e+243 1.16518628e+078 2.64619408e-260
  3.09456490e+169 1.10638849e+200]
 [2.26726982e+161 1.28625507e+248 6.08709904e+247 2.32160960e-152
  1.96930938e+243 1.78714831e+161 1.39335457e-258 1.67494802e+243
  1.05953945e+277 6.38805124e+029]
 [1.07564651e+272 1.02768316e+248 2.60985693e+180 1.15314140e+214
  9.13611906e+242 5.49034489e-096 4.36373655e+169 1.38957138e-118
  1.04991114e-153 5.48854470e-096]
 [2.99507597e+209 4.95238571e+223 2.19527311e-152 1.62691065e+219
  5.36094582e+199 7.08468655e+159 7.22759585e+159 4.23274456e+175
  6.62907841e+265 8.47985251e+164]
 [1.77942355e+248 1.46915539e+195 2.87908278e+214 5.02623426e+180
  2.42774682e-154 9.10434185e+276 1.35452195e+243 4.62197489e+228
  5.48946895e-096 5.48854470e-096

In [ ]:
import numpy as np
a=np.arange(1,100)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [ ]:
a=np.arange(1,100)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [ ]:
a=np.arange(12)
print(a)
b=a.reshape(3,4)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
import numpy as np

print(np.__version__)


2.0.2


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)


[1 2 3 4 5]


In [ ]:
a=np.array([10,20,30,40,50])
print(a[0])

10


In [ ]:
a=np.array([10,20,30,40,50])
print(a[-5
        ])

10


In [ ]:
import numpy as np

arr = np.array(42)

print(arr)


42


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.ndim)
print(arr)


2
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)
print(arr.ndim)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
3


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [ ]:
import numpy as np
arr = np.array([[[1, 2], [3, 4],[5,6],[6,7]], [[5, 6], [7, 8],[9,10],[11,10]]])
print(arr[1])


[[ 5  6]
 [ 7  8]
 [ 9 10]
 [11 10]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[1
          ])



2


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0] + arr[1])


3


In [ ]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])


2nd element on 1st row:  2


In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])


6


In [ ]:
a=np.array([1,2,3,4,5,])
b=np.array([10,20,30,40,50,])
print(a+b)
print(a*b)
print(a**2)
print(b**2)

[11 22 33 44 55]
[ 10  40  90 160 250]
[ 1  4  9 16 25]
[ 100  400  900 1600 2500]


In [ ]:
import pandas as pd
print(pd.__version__)

2.2.2


In [ ]:
from google.colab import files
uploaded = files.upload()

Saving students_marks.csv to students_marks.csv


In [ ]:
import pandas as pd
df = pd.read_csv("students_marks.csv")
print(df)

   ID  Student Name  Math  Science  English  History  Computer  Total Marks
0   1  Aarav Sharma    60      100       49       65        81          355
1   2   Priya Verma    43       44       92       74        46          299
2   3   Rohan Gupta    63       77       43       98        72          353
3   4  Ananya Singh    53       42       45       67        66          273
4   5   Karan Mehta    44       55       45       75        67          286
5   6    Isha Patel    43       92       76       47       100          358
6   7    Vikram Rao    54       80       80       77       100          391
7   8   Neha Kapoor    43       76       77       65        43          304
8   9    Arjun Nair    54       42       75       94        48          313
9  10   Sneha Joshi    58       66       49       74        47          294


In [ ]:
marks = pd.Series([60,70,80],index=["A","b","C"])
print(marks)

A    60
b    70
C    80
dtype: int64


In [ ]:
marks = pd.Series([60,70,80],index=[1,2,3])
print(marks)

1    60
2    70
3    80
dtype: int64


In [ ]:
from google.colab import files
uploaded = files.upload()


Saving employees.csv to employees.csv


In [ ]:
import pandas as pd
df = pd.read_csv("employees.csv")
print(df)

   Employee ID               Name  Salary       Department
0       EMP001     James Anderson   55000            Sales
1       EMP002       Maria Garcia   62000        Marketing
2       EMP003     Robert Johnson   48000          Support
3       EMP004     Linda Martinez   71000      Engineering
4       EMP005      Michael Brown   58000          Finance
5       EMP006     Patricia Davis   66000  Human Resources
6       EMP007       David Wilson   53000            Sales
7       EMP008      Barbara Moore   75000      Engineering
8       EMP009     William Taylor   49000          Support
9       EMP010   Elizabeth Thomas   68000        Marketing
10      EMP011    Richard Jackson   72000      Engineering
11      EMP012     Jennifer White   54000          Finance
12      EMP013     Charles Harris   61000            Sales
13      EMP014       Susan Martin   59000  Human Resources
14      EMP015    Joseph Thompson   77000      Engineering
15      EMP016     Jessica Garcia   50000          Suppo

In [ ]:
import pandas as pd
df = pd.read_csv("employees.csv")
print(df)

In [ ]:
from google.colab import files
uploaded = files.upload()



Saving employees.csv to employees (1).csv


In [ ]:
import pandas as pd
df = pd.read_csv("employees.csv")
print(df)

   Employee ID               Name  Salary       Department
0       EMP001     James Anderson   55000            Sales
1       EMP002       Maria Garcia   62000        Marketing
2       EMP003     Robert Johnson   48000          Support
3       EMP004     Linda Martinez   71000      Engineering
4       EMP005      Michael Brown   58000          Finance
5       EMP006     Patricia Davis   66000  Human Resources
6       EMP007       David Wilson   53000            Sales
7       EMP008      Barbara Moore   75000      Engineering
8       EMP009     William Taylor   49000          Support
9       EMP010   Elizabeth Thomas   68000        Marketing
10      EMP011    Richard Jackson   72000      Engineering
11      EMP012     Jennifer White   54000          Finance
12      EMP013     Charles Harris   61000            Sales
13      EMP014       Susan Martin   59000  Human Resources
14      EMP015    Joseph Thompson   77000      Engineering
15      EMP016     Jessica Garcia   50000          Suppo

In [ ]:
df["Bonus"]=5000
print(df)


   Employee ID               Name  Salary       Department  Bonus
0       EMP001     James Anderson   55000            Sales   5000
1       EMP002       Maria Garcia   62000        Marketing   5000
2       EMP003     Robert Johnson   48000          Support   5000
3       EMP004     Linda Martinez   71000      Engineering   5000
4       EMP005      Michael Brown   58000          Finance   5000
5       EMP006     Patricia Davis   66000  Human Resources   5000
6       EMP007       David Wilson   53000            Sales   5000
7       EMP008      Barbara Moore   75000      Engineering   5000
8       EMP009     William Taylor   49000          Support   5000
9       EMP010   Elizabeth Thomas   68000        Marketing   5000
10      EMP011    Richard Jackson   72000      Engineering   5000
11      EMP012     Jennifer White   54000          Finance   5000
12      EMP013     Charles Harris   61000            Sales   5000
13      EMP014       Susan Martin   59000  Human Resources   5000
14      EM

In [ ]:
df["Total"]=df["Salary"]+df["Bonus"]
print(df)

   Employee ID               Name  Salary       Department  Bonus  Total
0       EMP001     James Anderson   55000            Sales   5000  60000
1       EMP002       Maria Garcia   62000        Marketing   5000  67000
2       EMP003     Robert Johnson   48000          Support   5000  53000
3       EMP004     Linda Martinez   71000      Engineering   5000  76000
4       EMP005      Michael Brown   58000          Finance   5000  63000
5       EMP006     Patricia Davis   66000  Human Resources   5000  71000
6       EMP007       David Wilson   53000            Sales   5000  58000
7       EMP008      Barbara Moore   75000      Engineering   5000  80000
8       EMP009     William Taylor   49000          Support   5000  54000
9       EMP010   Elizabeth Thomas   68000        Marketing   5000  73000
10      EMP011    Richard Jackson   72000      Engineering   5000  77000
11      EMP012     Jennifer White   54000          Finance   5000  59000
12      EMP013     Charles Harris   61000          

In [ ]:
df.groupby("Department")["Salary"].sum()


,Salary
Department,
Engineering,695000
Finance,527000
Human Resources,509000
Marketing,522000
Sales,510000
Support,402000


In [ ]:
df["Branch"]="CSE"
print(df)

   Employee ID               Name  Salary       Department  Bonus  Total  \
0       EMP001     James Anderson   55000            Sales   5000  60000   
1       EMP002       Maria Garcia   62000        Marketing   5000  67000   
2       EMP003     Robert Johnson   48000          Support   5000  53000   
3       EMP004     Linda Martinez   71000      Engineering   5000  76000   
4       EMP005      Michael Brown   58000          Finance   5000  63000   
5       EMP006     Patricia Davis   66000  Human Resources   5000  71000   
6       EMP007       David Wilson   53000            Sales   5000  58000   
7       EMP008      Barbara Moore   75000      Engineering   5000  80000   
8       EMP009     William Taylor   49000          Support   5000  54000   
9       EMP010   Elizabeth Thomas   68000        Marketing   5000  73000   
10      EMP011    Richard Jackson   72000      Engineering   5000  77000   
11      EMP012     Jennifer White   54000          Finance   5000  59000   
12      EMP0

In [ ]:
from google.colab import files
uploaded = files.upload()



Saving employees.xlsx to employees.xlsx


In [ ]:
df=pd.read_excel("employees.xlsx")
print(df)


  Employee ID           Name       Department               Role  Salary
0       E1001  Ananya Sharma      Engineering  Software Engineer   85000
1       E1002    Rohan Verma        Marketing  Marketing Manager   72000
2       E1003     Priya Nair  Human Resources       HR Executive   55000
3       E1004    Karan Mehta          Finance  Financial Analyst   68000
4       E1005    Sneha Gupta            Sales    Sales Executive   60000


In [ ]:
df.to_excel("employees.xlsx",index= False)
print(df)

  Employee ID           Name       Department               Role  Salary
0       E1001  Ananya Sharma      Engineering  Software Engineer   85000
1       E1002    Rohan Verma        Marketing  Marketing Manager   72000
2       E1003     Priya Nair  Human Resources       HR Executive   55000
3       E1004    Karan Mehta          Finance  Financial Analyst   68000
4       E1005    Sneha Gupta            Sales    Sales Executive   60000


In [ ]:
print(df.isnull())

   Employee ID   Name  Department   Role  Salary
0        False  False       False  False   False
1        False  False       False  False   False
2        False  False       False  False   False
3        False  False       False  False   False
4        False  False       False  False   False


In [ ]:
df["Tax"]="null"
print(df)

  Employee ID           Name       Department               Role  Salary   Tax
0       E1001  Ananya Sharma      Engineering  Software Engineer   85000  null
1       E1002    Rohan Verma        Marketing  Marketing Manager   72000  null
2       E1003     Priya Nair  Human Resources       HR Executive   55000  null
3       E1004    Karan Mehta          Finance  Financial Analyst   68000  null
4       E1005    Sneha Gupta            Sales    Sales Executive   60000  null


In [ ]:
df["Sales"]="null"
print(df)

  Employee ID           Name       Department               Role  Salary  \
0       E1001  Ananya Sharma      Engineering  Software Engineer   85000   
1       E1002    Rohan Verma        Marketing  Marketing Manager   72000   
2       E1003     Priya Nair  Human Resources       HR Executive   55000   
3       E1004    Karan Mehta          Finance  Financial Analyst   68000   
4       E1005    Sneha Gupta            Sales    Sales Executive   60000   

    Tax Sales  
0  null  null  
1  null  null  
2  null  null  
3  null  null  
4  null  null  


In [ ]:
print(df.isnull())

   Employee ID   Name  Department   Role  Salary    Tax  Sales
0        False  False       False  False   False  False  False
1        False  False       False  False   False  False  False
2        False  False       False  False   False  False  False
3        False  False       False  False   False  False  False
4        False  False       False  False   False  False  False


In [2]:
!curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
!echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
!apt update
!apt install gh -y

8+1 records in
8+1 records out
4528 bytes (4.5 kB, 4.4 KiB) copied, 0.134886 s, 33.6 kB/s
Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:7 https://cli.github.com/packages stable/main amd64 Packages [355 B]
Get:8 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [101 kB]
Get:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:12 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [10.6 MB]
Get:13 http://sec